apiVersion: v1
kind: ConfigMap
metadata:
  name: coffee-and-tea-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/CoffeeAndTea"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "admin"
